[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "mol-aspect"
dynamic = ["version"]
authors = [
  { name="Mitsuru Ohno", email="pejpohn@gmail.com" },
]
description = "Calculate molecular aspect ratios by PCA and view principal axes in 3D"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Chemistry",
    "License :: OSI Approved :: BSD License",
]
license = "BSD-3-Clause"
license-files = ["LICENSE*"]

dependencies = [
    "numpy >= 2.0.2",
    "rdkit >= 2024.3.1",
    "py3Dmol >= 2.4.0",
]

[tool.hatch.version]
path = "src/molaspect/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["src/molaspect"]

[project.urls]
Homepage = "https://github.com/PEJpOhno/mol-aspect"
Issues = "https://github.com/PEJpOhno/mol-aspect/issues"
